language: node_js
node_js:
  - "node"
env:
  global:
    - secure: BthCG4QxXhuKAQUa9t6nZHfggXUaeTgZVfwKFLrIh8JrLOhyR9/at2LyZwWcA4EAQAdUjPQTTejcDgPXIqXSsgB16P0m4ZW5J7nJmBsk17uxV5ymYzJmykn1fK5ANWCiylC6zFUYFwK6XD+lazOy0p0R9qohRI8rU1g/ILnZ7ebrkki+VnbeZpe6CJJyPfuYH7CaiCWTTqykJB55M5NJLZj/BnygMAoqPqQdX/EmKfWvV+iDAeS2Kaxh2XyK6R4fnTZz4iY6eUXhcMfnJt78ddtkSb/TXR7i3tmHpLaCx45LCo3+5TbXMaYd4mjrBaxmfMBWp4y13lC9Zqflo5UZZLjUpA/7CSDqdt7yrInAiuDRhjGxHLoSHHttNxHrPhPaAtU9OmAIIba5kaLeWl1CTDS2hT3lk8JBWzitGz03b2mnyNiYIgMQ3vtrNR5cAMcpYn9/tMSgpOXdgllvDqEpkGGcNocOGpTiJCNLZVeHauYQY0yRBKesnTdIcZhWmD4FwLnIa0wbd9UbGIQd8HpsnwzL7vLGSwmmsT9A7Qw5cwQWzzu34OsN+WV1M5bWxcaRj64+WXuMXsjN36MBBTn5DaCwtYwhWIOPXz548UxezktW565Sn2iWNj6kvBWPoN7kl0O5PJ6VN47oHhHeHOrPvdxFXvHr4rCQAy6Pwn3mMH8=
after_success: npm run coverage
